# Generated by Django 4.2 on 2025-12-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='category',
            field=models.CharField(choices=[('USER', 'User Activity'), ('SYSTEM', 'System Event'), ('SECURITY', 'Security'), ('OTHER', 'Other')], default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='details_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10),
        ),
    ]
