# Generated by Django 4.2 on 2025-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='classification',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('TOP_SECRET', 'Top Secret')], default='INTERNAL', max_length=20),
        ),
    ]
