# Generated by Django 4.2 on 2025-12-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='classification',
            field=models.CharField(choices=[('UNCLASSIFIED', 'Unclassified'), ('CONFIDENTIAL', 'Confidential'), ('SECRET', 'Secret'), ('TOP_SECRET', 'Top Secret')], default='UNCLASSIFIED', max_length=20),
        ),
    ]
