# Generated by Django 4.2 on 2025-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('LEAVE', 'Leave Request')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
