# Generated by Django 4.2 on 2025-12-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Employee'), (1, 'Manager'), (2, 'Senior Manager'), (3, 'Director'), (99, 'Admin')], default=0),
        ),
    ]
