# Generated by Django 4.2 on 2025-12-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Employee'), (1, 'Manager'), (2, 'Senior Manager'), (3, 'Director'), (4, 'Quality Assurance'), (99, 'Admin')], default=0),
        ),
    ]
