# Generated by Django 4.2 on 2025-12-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('FINANCE', 'Finance'), ('OPERATIONS', 'Operations'), ('SALES', 'Sales'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_after_hours_preapproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'Employee'), (1, 'Manager'), (2, 'Senior Manager'), (3, 'Director'), (99, 'Admin')], default=0),
        ),
    ]
