# Generated by Django 4.2 on 2025-12-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_role_data'),
        ('accounts', '0006_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
    ]
